### ISSUE TITLE
Notice on end script, can this be ignored?

### ISSUE THREAD

**Issue by BlackTiger63** [INUI-Dev/IPTV#1]
On the end of installA.sh this is shown:
```
Processing triggers for libc-bin (2.23-0ubuntu11) ...
Processing triggers for ureadahead (0.100.0-19.1) ...
Processing triggers for systemd (229-4ubuntu21.22) ...
Processing triggers for vlc-nox (2.2.2-5ubuntu0.16.04.4) ...
W: --force-yes is deprecated, use one of the options starting with --allow instead.
```
After this, the install.sh is ready. But It's odd seeing this last line starting with the W about the --foce-yes. Can this be safely ignored or is something missing

**Comment by cryptoel** [comment]
Yes Deprecated still works it's just telling you that --allow is the updated version.

**Comment by cryptoel** [comment]
> On the end of installA.sh this is shown:
> 
> ```
> Processing triggers for libc-bin (2.23-0ubuntu11) ...
> Processing triggers for ureadahead (0.100.0-19.1) ...
> Processing triggers for systemd (229-4ubuntu21.22) ...
> Processing triggers for vlc-nox (2.2.2-5ubuntu0.16.04.4) ...
> W: --force-yes is deprecated, use one of the options starting with --allow instead.
> ```
> 
> After this, the install.sh is ready. But It's odd seeing this last line starting with the W about the --foce-yes. Can this be safely ignored or is something missing

Yes Deprecated still works it's just telling you that --allow is the updated command.
